# Generated by Django 4.1.6 on 2023-05-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('pickup_date_time', models.DateTimeField()),
                ('small_bottles', models.IntegerField()),
                ('large_bottles', models.IntegerField()),
                ('donation_percentage', models.IntegerField(choices=[(0, '0%'), (10, '10%'), (25, '25%'), (50, '50%'), (100, '100%')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
        ),
    ]
