# Generated by Django 4.1.6 on 2023-05-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='pickup_date_time',
            field=models.DateField(),
        ),
    ]
